version: '3.4'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ../data/db/app:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  app:
    image: app
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
      - 5678:5678
    environment:
      - POSTGRES_NAME=app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      - db
